version: '2.1'

services:
  heroes-node-api:
    image: heroes-node-api
    build: .
    environment:
      NODE_ENV: production
    restart: always
    ports:
      - 7777:7777
    command: npm start
